# .github/workflows/dependency-graph.yml
name: Update Dependency Graph

on:
  push:
    branches:
      - master # default branch of the project

jobs:
  update-graph:
    name: Update Dependency Graph
    runs-on: adoptopenjdk/openjdk8
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
